# Site settings
title: Lisa Bormann
domain: lisabormann.com
email: lisabormann@comcast.net
description: "Lisa Bormannâ€™s paintings are done from life, primarily in oil and pastel. Focusing on contemporary figure painting in her Minneapolis studio, she also spends several months a year painting landscapes on site, particularly on Lake Superior and along the Mississipi river valley."


# Google Tag Manager Id
gtmId: GTM-TMNN7H

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '000000'
  secondary: '2c3651'
  secondary-dark: '2c3651'
  
# Footer settings
footer:
  copyright: Lisa Bormann

# Build settings
markdown: kramdown
permalink: pretty
